const allComponents = [
  'Dashboard',
  'Requested Leaves',
  'Interviews',
  'Candidate List',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation',
  'Resignation Applications',
  'Employees Master',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'My Profile',
  'Employees Transfer',
  'Applicant List',
  'Dashboard',
  'Requested Leaves',
  'Interviews',
  'Candidate List',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation',
  'Resignation Applications',
  'Employees Master',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'My Profile',
  'Employees Transfer',
  'Applicant List',
  'Role Assignment',
  'Dashboard',
  'Access Assignment',
  'Access Management',
  'Openings',
  'Employees Master',
  'Requested Leaves',
  'Interviews',
  'Candidate List',
  'Leave',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Add Location',
  'Locations',
  'Designations',
  'Departments',
  'Seat',
  'Resignation',
  'Resignation Applications',
  'Applicant List',
  'Add Applicant',
  'OnBoard Form',
  'Interview Form',
  'Openings List View',
  'jdupload',
  'Payroll',
  'Paid By Bank',
  'Given To Bank',
  'Return By Bank',
  'Weekly-off Holiday',
  'Weekly-off Policy',
  'Employee Salary Add-ons',
  'Employee Deduction',
  'Employee Leaves',
  'Resignation Status',
  'Resignation (Self)',
  'Resignation (Others)',
  'Summary',
  'Location Master',
  'Bgt Seat Master',
  'EmpCode Seat Master',
  'Location Master View',
  'Bgt Seat Master View',
  'Emp Code Seat Master',
  'Emp Attendnace',
  'Emp Deduction',
  'Applicability',
  'Emp Salary Structure',
  'Salary',
  'Month Salary',
  'Payable Days',
  'Leave',
  'Comp Off',
  'Earned Leaves',
  'Casual Leaves',
  'Gross Earning',
  'Deduction',
  'PF',
  'ESI',
  'Gratuity & Bonus',
  'Leave Opening Balance',
  'Emp Personal Details',
  'Emp Statutory Details',
  'Emp Degree Qualifications',
  'Emp Past Experience',
  'Emp Joining Releaving',
  'Emp Revised Dept-Desg-Loc',
  'Salary Slips',
  'LOC & EMP',
  'Salary Paid Status',
  'Leave Master',
  'Bgt Salary Structure',
  'Gross Earning Details',
  'Deduction Details',
  'Gratuity & Bonus',
  'Leaves Status',
  'Additional Payment',
  'Net Payable',
  'Gratutiy & Bonus',
  'Emp Salary Status',
  'My Leaves',
  'Comp Off',
  'Salary Recalculate',
  'Salary Summery',
  'Employees Transfer',
  'Profile Update Application',
  'My Profile',
  'New Stores',
  'Shift Alignment',
  'Paid By Cash',
  'Salary Recalculate',
  'Document Generate',
  'F&F',
  'Requested Leaves',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation',
  'Paid By Bank',
  'Given To Bank',
  'Return By Bank',
  'Salary Slips',
  'My Leaves',
  'My Profile',
  'Resignation Status',
  'Resignation (Self)',
  'Resignation (Others)',
  'Dashboard',
  'Access Assignment',
  'Access Management',
  'Openings',
  'Employees Master',
  'Requested Leaves',
  'Interviews',
  'Candidate List',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Add Location',
  'Locations',
  'Designations',
  'Departments',
  'Seat',
  'Resignation',
  'Resignation Applications',
  'Applicant List',
  'Add Applicant',
  'OnBoard Form',
  'Interview Form',
  'Openings List View',
  'jdupload',
  'Resignation Status',
  'Resignation (Self)',
  'Resignation (Others)',
  'View Interview Form',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'Employees Transfer',
  'My Profile',
  'New Stores',
  'Store Routing',
  'Store Routing View',
  'Dashboard',
  'Access Assignment',
  'Access Management',
  'Openings',
  'Employees Master',
  'Requested Leaves',
  'Interviews',
  'Candidate List',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Locations',
  'Designations',
  'Departments',
  'Seat',
  'Resignation',
  'Resignation Applications',
  'Applicant List',
  'Add Applicant',
  'OnBoard Form',
  'Interview Form',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'Salary Controll Panel',
  'My Profile',
  'Employees Transfer',
  'Resignation (Self)',
  'Salary Recalculate',
  'Document Generate',
  'New Stores',
  'Store Routing',
  'Store Routing View',
  'Dashboard',
  'Requested Leaves',
  'Interviews',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation (Self)',
  'Resignation (Others)',
  'Resignation Status',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'My Profile',
  'Details',
  'Applicant List',
  'Dashboard',
  'Requested Leaves',
  'Interviews',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation (Self)',
  'Resignation (Others)',
  'Resignation Status',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'Employees Master',
  'My Profile',
  'Employees Transfer',
  'Candidate List',
  'Applicant List',
  'Dashboard',
  'Requested Leaves',
  'Interviews',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation (Self)',
  'Resignation (Others)',
  'Resignation Status',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'Employees Master',
  'My Profile',
  'Employees Transfer',
  'Candidate List',
  'Applicant List',
  'Dashboard',
  'Requested Leaves',
  'Interviews',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation (Self)',
  'Resignation (Others)',
  'Resignation Status',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'Employees Master',
  'My Profile',
  'Employees Transfer',
  'Candidate List',
  'Applicant List',
  'OnBoard Form',
  'Dashboard',
  'Requested Leaves',
  'Candidate List',
  'Attendance',
  'Team Attendance',
  'Regularize Request',
  'Resignation',
  'Resignation Applications',
  'Employees Master',
  'Salary Slips',
  'Leaves Status',
  'My Leaves',
  'My Profile',
  'Employees Transfer',
  'New Employee',
  'Resignation (Self)',
  'Applicant List',
  'Add Applicant',
]

const uniqueComponents = [...new Set(allComponents)]

export default uniqueComponents
