const columns = [
  {
    title: 'State',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Code',
    dataIndex: '',
    key: '',
    width: 80,
    ellipsis: true,
  },
  {
    title: 'Name',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Act OP-DT',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Bgt OP-DT',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Area New',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Zone',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Reg',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Cluster',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Emp Code',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'Emp Name',
    dataIndex: '',
    key: '',
    width: 120,
    ellipsis: true,
  },
  {
    title: 'Month',
    dataIndex: '',
    key: '',
    width: 90,
    ellipsis: true,
  },
  {
    title: 'EL',
    dataIndex: '',
    key: '',
    width: 80,
    ellipsis: true,
  },
  {
    title: 'CL',
    dataIndex: '',
    key: '',
    width: 80,
    ellipsis: true,
  },
  {
    title: 'Comp Off',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
  {
    title: 'SL',
    dataIndex: '',
    key: '',
    width: 80,
    ellipsis: true,
  },
  {
    title: 'Screen HL',
    dataIndex: '',
    key: '',
    width: 110,
    ellipsis: true,
  },
  {
    title: 'Training',
    dataIndex: '',
    key: '',
    width: 100,
    ellipsis: true,
  },
]

const totalWidth = columns.reduce((acc, col) => acc + (col.width || 150), 0)

export { columns, totalWidth }
