const columns = [
  {
    title: 'State',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Code',
    dataIndex: 'code',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Name',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Act OP-DT',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Bgt OP-DT',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Area New',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Zone',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Reg',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Cluster',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Emp Code',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Emp Name',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Emp Gross Salary',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Registration Applicable',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Registration Site',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Registration Emp',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'LWF SITE CD/REF',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Freq',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Total Amount',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Ded Emp CNTB %',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Ded Emp CNTB Amount',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Ded Empr CNTB %',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Ded Empr CNTB Amount',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Auth',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Amount',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Freq',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Due Dt',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'H Link Auth',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'H Link TTRL',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Diff',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Remarks',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Screen HL',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Training',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Applicable',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deduction Freq',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Emp Contribution Amount %',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Empr Contribution Amount %',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
]

const ttlWidth = columns.reduce((acc, col) => acc + col.width, 0)

export { columns, ttlWidth }
