const columns = [
  {
    title: 'State',
    dataIndex: 'stateName',
    key: 'stateName',
    ellipsis: true,
    width: 150,
  },
  {
    title: ' Loc Code',
    dataIndex: 'locationCode',
    key: 'locationCode',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Loc Name',
    dataIndex: 'state',
    key: 'code',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deduc Frequency',
    dataIndex: 'deductionFreq',
    key: 'deductionFreq',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deduc Ttl Amt',
    dataIndex: 'deductionTotalAmount',
    key: 'deductionTotalAmount',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Emp CNTB %',
    dataIndex: 'empCntbPer',
    key: 'empCntbPer',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Emp CNTB Amount',
    dataIndex: 'empCntbAmount',
    key: 'empCntbAmount',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Empr CNTB %',
    dataIndex: 'emplyrCntbPer',
    key: 'emplyrCntbPer',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Empr CNTB Amount',
    dataIndex: 'emplyrCntbAmount',
    key: 'emplyrCntbAmount',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Auth',
    dataIndex: 'depositAuth',
    key: 'depositAuth',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Amount',
    dataIndex: 'depositAmnt',
    key: 'depositAmnt',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Freq',
    dataIndex: 'depositFreq',
    key: 'depositFreq',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Deposit Due Dt',
    dataIndex: 'depositDueDate',
    key: 'depositDueDate',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'H Link Auth',
    dataIndex: 'hLinkAuth',
    key: 'hLinkAuth',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'H Link TTRL',
    dataIndex: 'hLinkTtrl',
    key: 'hLinkTtrl',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Diff',
    dataIndex: 'diffNote',
    key: 'diffNote',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Remarks',
    dataIndex: 'remarks',
    key: 'remarks',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Screen HL',
    dataIndex: 'screenHl',
    key: 'screenHl',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Training',
    dataIndex: 'training',
    key: 'training',
    ellipsis: true,
    width: 150,
  },
]

const ttlWidth = columns.reduce((acc, col) => acc + col.width, 0)

export { columns, ttlWidth }
