const columns = [
  {
    title: 'Batch No.',
    dataIndex: 'batchNo',
    key: 'batchNo',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Running Time',
    dataIndex: 'runAt',
    key: 'runAt',
    ellipsis: true,
    width: 170,
    render: (value) => {
      const date = String(value).split('T')[0]
      const time = String(value).split('T')[1]?.slice(0, 5)

      return `${date} - ${time}`
    },
  },
  {
    title: 'Month',
    dataIndex: 'month',
    key: 'month',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Emp Code',
    dataIndex: 'ecode',
    key: 'ecode',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Emp Name',
    dataIndex: 'employeeName',
    key: 'employeeName',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Loc Code',
    dataIndex: 'locationCode',
    key: 'locationCode',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Loc Name',
    dataIndex: 'locationName',
    key: 'locationName',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Department',
    dataIndex: 'department',
    key: 'department',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Designation',
    dataIndex: 'designation',
    key: 'designation',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Absent',
    dataIndex: 'absent',
    key: 'absent',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Act Ttl Days',
    dataIndex: 'actualTtlDays',
    key: 'actualTtlDays',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Act Weekly Days',
    dataIndex: 'actualWeekly',
    key: 'actualWeekly',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Arrear',
    dataIndex: 'arrear',
    key: 'arrear',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Basic Sal Act',
    dataIndex: 'basicSalaryActual',
    key: 'basicSalaryActual',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Basic Sal Bgt',
    dataIndex: 'basicSalaryBudget',
    key: 'basicSalaryBudget',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Books & Period. Act',
    dataIndex: 'booksAndPeriodicalsActual',
    key: 'booksAndPeriodicalsActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Books & Priod. Bgt',
    dataIndex: 'booksAndPeriodicalsBudget',
    key: 'booksAndPeriodicalsBudget',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CCA Act',
    dataIndex: 'ccaActual',
    key: 'ccaActual',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'CCA Bgt',
    dataIndex: 'ccaBudget',
    key: 'ccaBudget',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'DA Act',
    dataIndex: 'daActual',
    key: 'daActual',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'DA Bgt',
    dataIndex: 'daBudget',
    key: 'daBudget',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Driver Wages Act',
    dataIndex: 'driverWagesActual',
    key: 'driverWagesActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Driver Wages Bgt',
    dataIndex: 'driverWagesBudget',
    key: 'driverWagesBudget',
    ellipsis: true,
    width: 150,
  },

  {
    title: 'Fooding Allow.',
    dataIndex: 'foodingAllowance',
    key: 'foodingAllowance',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Cash Short',
    dataIndex: 'cashShort',
    key: 'cashShort',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CL Acq.',
    dataIndex: 'casualLeaveAcquired',
    key: 'casualLeaveAcquired',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CL Bal',
    dataIndex: 'casualLeaveBalance',
    key: 'casualLeaveBalance',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CL Used',
    dataIndex: 'casualLeaveUsed',
    key: 'casualLeaveUsed',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CompOff Acq',
    dataIndex: 'compoOffAcquired',
    key: 'compoOffAcquired',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CompOff Bal',
    dataIndex: 'compoOffBalance',
    key: 'compoOffBalance',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'CompOff Used',
    dataIndex: 'compoOffUsed',
    key: 'compoOffUsed',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'EL Acq',
    dataIndex: 'earnedLeaveAcquired',
    key: 'earnedLeaveAcquired',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'EL Bal',
    dataIndex: 'earnedLeaveBalance',
    key: 'earnedLeaveBalance',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'EL Used',
    dataIndex: 'earnedLeaveUsed',
    key: 'earnedLeaveUsed',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Diesel Deduction',
    dataIndex: 'dieselDeduction',
    key: 'dieselDeduction',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'ESIC Employee',
    dataIndex: 'esicEmployee',
    key: 'esicEmployee',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'ESIC Employer',
    dataIndex: 'esicEmployer',
    key: 'esicEmployer',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'ESIC Total',
    dataIndex: 'esicTotal',
    key: 'esicTotal',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Extra Day Allow',
    dataIndex: 'extraDayAllowance',
    key: 'extraDayAllowance',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Extra Days',
    dataIndex: 'extraDays',
    key: 'extraDays',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Holiday Off',
    dataIndex: 'holidayOff',
    key: 'holidayOff',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Incentive',
    dataIndex: 'incentive',
    key: 'incentive',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Leave Used',
    dataIndex: 'leaveUsed',
    key: 'leaveUsed',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Loan',
    dataIndex: 'loan',
    key: 'loan',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'LWF',
    dataIndex: 'lwf',
    key: 'lwf',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'LWP',
    dataIndex: 'lwp',
    key: 'lwp',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Machine',
    dataIndex: 'machine',
    key: 'machine',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Manual',
    dataIndex: 'manual',
    key: 'manual',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'HRA Act',
    dataIndex: 'hraActual',
    key: 'hraActual',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'HRA Bgt',
    dataIndex: 'hraBudget',
    key: 'hraBudget',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Fuel & Maint Act',
    dataIndex: 'fuelAndMaintenanceActual',
    key: 'fuelAndMaintenanceActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Fuel & Maint Bgt',
    dataIndex: 'fuelAndMaintenanceBudget',
    key: 'fuelAndMaintenanceBudget',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Meal Voucher Act',
    dataIndex: 'mealVoucherActual',
    key: 'mealVoucherActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Meal Vouvher Bgt',
    dataIndex: 'mealVoucherBudget',
    key: 'mealVoucherBudget',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Mobile Bill',
    dataIndex: 'mobileBill',
    key: 'mobileBill',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Mobile Bill Act',
    dataIndex: 'mobileBillActual',
    key: 'mobileBillActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Mobile Bill Bgt',
    dataIndex: 'mobileBillBudget',
    key: 'mobileBillBudget',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Monthly Gross CTC Act',
    dataIndex: 'monthlyGrossCTCActual',
    key: 'monthlyGrossCTCActual',
    ellipsis: true,
    width: 180,
  },
  {
    title: 'Monthly Gross CTC Bgt',
    dataIndex: 'monthlyGrossCTCBudget',
    key: 'monthlyGrossCTCBudget',
    ellipsis: true,
    width: 180,
  },
  {
    title: 'Monthly Gross CTC Act (After Deduction with AddOns)',
    dataIndex: 'monthlyGrossCTCActualAfterDeductionAndAddons',
    key: 'monthlyGrossCTCActualAfterDeductionAndAddons',
    ellipsis: true,
    width: 170,
  },
  {
    title: 'Opening CL',
    dataIndex: 'openingCL',
    key: 'openingCL',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Opening CompOff',
    dataIndex: 'openingCompoOff',
    key: 'openingCompoOff',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Opening EL',
    dataIndex: 'openingEL',
    key: 'openingEL',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Overtime',
    dataIndex: 'overtime',
    key: 'overtime',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'P Tax',
    dataIndex: 'pTax',
    key: 'pTax',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Payable Days',
    dataIndex: 'paybleDays',
    key: 'paybleDays',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Payable Days Final',
    dataIndex: 'paybleDaysFinal',
    key: 'paybleDaysFinal',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Penalty',
    dataIndex: 'penalty',
    key: 'penalty',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'PF Employee',
    dataIndex: 'pfEmployee',
    key: 'pfEmployee',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'PF Employer',
    dataIndex: 'pfEmployer',
    key: 'pfEmployer',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'PF Total',
    dataIndex: 'pfTotal',
    key: 'pfTotal',
    ellipsis: true,
    width: 120,
  },
  {
    title: 'Prof. Attire Act',
    dataIndex: 'professionalAttireActual',
    key: 'professionalAttireActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Prof. Attire Bgt',
    dataIndex: 'professionalAttireBudget',
    key: 'professionalAttireBudget',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Present WeeklyOff',
    dataIndex: 'presentWeeklyOff',
    key: 'presentWeeklyOff',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Reim Act',
    dataIndex: 'reimbursementActual',
    key: 'reimbursementActual',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Reim Bgt',
    dataIndex: 'reimbursementBudget',
    key: 'reimbursementBudget',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Special Allow Act',
    dataIndex: 'specialAllowanceActual',
    key: 'specialAllowanceActual',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Special Allow Bgt',
    dataIndex: 'specialAllowanceBudget',
    key: 'specialAllowanceBudget',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'TDS',
    dataIndex: 'tds',
    key: 'tds',
    ellipsis: true,
    width: 100,
  },
  {
    title: 'Total Deductions',
    dataIndex: 'totalDeductions',
    key: 'totalDeductions',
    ellipsis: true,
    width: 150,
  },
  {
    title: 'Total Bgt Days',
    dataIndex: 'ttlBgtDays',
    key: 'ttlBgtDays',
    ellipsis: true,
    width: 150,
  },
]

const totalWidth = columns.reduce((acc, col) => acc + (col.width || 150), 0)

export { columns, totalWidth }
